import { StyleSheet } from "react-native";
import {
  useFonts,
  NunitoSans_200ExtraLight,
  NunitoSans_200ExtraLight_Italic,
  NunitoSans_300Light,
  NunitoSans_300Light_Italic,
  NunitoSans_400Regular,
  NunitoSans_400Regular_Italic,
  NunitoSans_600SemiBold,
  NunitoSans_600SemiBold_Italic,
  NunitoSans_700Bold,
  NunitoSans_700Bold_Italic,
  NunitoSans_800ExtraBold,
  NunitoSans_800ExtraBold_Italic,
  NunitoSans_900Black,
  NunitoSans_900Black_Italic,
} from "@expo-google-fonts/nunito-sans";

const stylesNw = StyleSheet.create({
  container: {
    flexDirection: "column",
    display: "flex",
    zIndex: 0,
    backgroundColor: "#FFC232",
  },
  cardProduto: {
    justifyContent: "space-between",
    backgroundColor: "#FF7070",
    flexDirection: "row",
    alignItems: "center",
    shadowRadius: 10,
    shadowOffset: { width: 5, height: 7 },
    shadowOpacity: 0.15,
    marginHorizontal: 5,
    paddingVertical: 15,
    marginVertical: 5,
    borderRadius: 20,
    paddingLeft: 15,
    height: 100,
    zIndex: 0,
    display: "flex",
  },

  cardText: {
    textAlign: "center",
    marginVertical: 2,
    fontWeight: "bold",
    fontSize: "1.1rem",
    fontFamily: "NunitoSans_700Bold",
    fontStyle: "normal",
    color: "#fff",
  },
  cardImage: {
    resizeMode: "cover",
    borderTopLeftRadius: 100,
    borderBottomLeftRadius: 100,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    height: 100,
    width: 200,
    zIndex: 1,
  },
  comandaIcon: {
    backgroundColor: "#FF7090",
    alignSelf: "flex-end",
    position: "fixed",
    borderRadius: 100,
    tintColor: "#FFF",
    top: "35rem",
    padding: 15,
    margin: 10,
    zIndex: 1,
    shadowRadius: 5,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.25,
  },
});
export { stylesNw };
